### PR TITLE
init DAQ data type update

### PR DESCRIPTION
**Pull request by LukeOxley**
Added signed integer types and floats. 
The signal bit length is only specifiable when the data type is unsigned and floats default to 32 bits.
In addition, more signal parameters can be added such as scale, offset, minimum, maximum, and units.
The scaling and offset are applied as (x * scale) / offset whenever the message is decoded.
However, they are not automatically applied whenever you send the message.
In addition, the units are displayed in the DAQ app under the frame viewer and plot axis labels.

### CODE REVIEW

**Comment by AdamBusch** [comment]
Is it `(x * scale) / offset` or `(x * scale) + offset`?

**Comment by AdamBusch** [comment]
ah looks like its +, looks good!

**Review by AdamBusch — APPROVED** [review]
nice units!

**Comment by LukeOxley** [comment]
@AdamBusch  my bad, it is (x * scale) + offset, this is also reflected in the can schema

**Pull request merged**
